### ISSUE TITLE
[Question] Recontruct && Building cost map failed

### ISSUE THREAD

**Issue by fan-ziqi** [leggedrobotics/viplanner#35]
# Question

## Color space

I reconstruct Carla and Matterport, but the colors are different from those in the paper. In the paper, the traversable area should be green. I noticed that Carla's colors follow `mpcat40`, for example, the floor is `#708090`. So how can the colors be mapped to ViPlanner? I’d like to know if the colors need to mapped to ViPlanner’s color space.

![carla](https://github.com/user-attachments/assets/6130cc31-e8c8-4259-a4e3-f832121fba07)

![matterport](https://github.com/user-attachments/assets/1a4550f9-8d0e-4d07-8c0c-cb13780d501c)

![paper](https://github.com/user-attachments/assets/9253ca48-abd3-412a-bf67-63a32705961c)

## Cost map

An error also occurred when building the cost map.

```bash
============ Creating Semantic Map from cloud ===============
COST-MAP INIT START
start loading and filtering point cloud from: cloud.ply
cost map size set to: 4130 x 4720
Map parameters changed!
Traceback (most recent call last):
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/viplanner/cost_builder.py", line 51, in <module>
    main(cfg)
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/viplanner/cost_builder.py", line 19, in main
    sem_cost_map.pcd_init()
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/viplanner/cost_maps/sem_cost_map.py", line 117, in pcd_init
    self.height_map = self._pcd_ground_height_map(self.pcd)
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/viplanner/cost_maps/sem_cost_map.py", line 183, in _pcd_ground_height_map
    height_pts_ground[~pts_ground] = pts_ground_location[non_ground_neighbor_idx, 2]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
It seems that `pts_idx_of_class` is empty in the following function

```python
    def _class_mapping(self) -> np.ndarray:
        # get colors
        color = np.asarray(self.pcd_filtered.colors) * 255.0

        # pts to class idx array
        pts_class_idx = np.ones(color.shape[0], dtype=int) * -1

        # assign each point to a class
        color = color.astype(int)
        for class_idx, class_color in enumerate(self.sem_meta.colors):
            pts_idx_of_class = (color == class_color).all(axis=1).nonzero()[0]
            pts_class_idx[pts_idx_of_class] = class_idx

        # identify points with unknown classes --> remove from point cloud
        known_idx = np.where(pts_class_idx != -1)[0]
        self.pcd_filtered = self.pcd_filtered.select_by_index(known_idx)
        print(f"Class of {len(known_idx)} points identified" f" ({len(known_idx) / len(color)} %).")

        return pts_class_idx[known_idx]
```

## Recontruct script

When I use `check_env_reconstruction.py` in `orbit_env`, the cloud looks fine. However, when I use `depth_reconstruct.py` in `ViPlanner`, it generates this kind of cloud. Could this be a bug?

![matterport_error](https://github.com/user-attachments/assets/57e8c5d0-9c8e-4c0d-b7db-67b3384ae776)

![carla_error](https://github.com/user-attachments/assets/023a8741-6a41-44ca-bd84-4d995487b216)

**Looking forward to and appreciate your response.**

**Comment by fan-ziqi** [comment]
fix in https://github.com/fan-ziqi/viplanner_data_generator
